# Generated by Django 4.0.3 on 2024-05-30 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_appointment_medicine_remove_medicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicines', models.ManyToManyField(blank=True, to='contrib.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_sold', to='contrib.patient')),
            ],
        ),
    ]
