# Generated by Django 5.0.6 on 2024-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_medicinesold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Gynecologist', 'Gynecologist'), ('Oncologist', 'Oncologist'), ('ENT Specialist', 'ENT Specialist'), ('Urologist', 'Urologist'), ('Endocrinologist', 'Endocrinologist'), ('General', 'General')], default=None, max_length=100),
        ),
    ]
